language: node_js
install:
  - npm install
script:
  - npm test
  - npm run styleguide:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: styleguide