language: node_js
install:
  - npm install
script:
  - npm install codecov -g
  - npm run test
  - npm run styleguide:build
after_success:
  - codecov
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: styleguide